### ISSUE TITLE
dogecoin/docker repository

### ISSUE THREAD

**Issue by AbcSxyZ** [Nyxtend/dogecoin-container#2]
Hello guys,

While exploring GitHub, I found your repository. Just a message to let you know there is currently an initiative to provide a Docker Hub implementation at https://github.com/dogecoin/docker.

Work is still in progress, but a working Dockerfile/entrypoint to build an image manually is already available, it may facilitate your work !
It's already functional and more complete : cross architecture (Debian only), arguments as environment variables, checksum verifications, user permissions... See docs in PR https://github.com/dogecoin/docker/pull/13. We're actually working on tests, some extra work is needed to be ready for Docker Hub, but it's on the way :)

And of course, any help is welcome <3 !

**Comment by Burke9077** [comment]
Thank you for bringing this to my attention! I've added myself as a watcher to that repo, long term I'd much prefer to use the official repo instead of building our own.

I've added a notice to the readme to point to the official repo -- thanks again!
